# fly.toml app configuration file generated for phaseon on 2024-09-26T02:16:08+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phaseon'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

  [[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  script_checks = []

  [[services.http_routes]]
  handlers = ["static"]
  match = "*"
  
  [[services.http_routes]]
  match = "*"
  handlers = ["rewrite"]
  rewrite = { path = "/index.html" }
